import { useMemo } from "react";
import { View, Text, ScrollView, StyleSheet, TouchableOpacity, Platform } from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ArrowLeft } from "phosphor-react-native";
import Colors, { C, cardShadow, useThemeColors, type ThemeColors } from "@/constants/colors";

const TERMS_VERSION = "1.0";
const EFFECTIVE_DATE = "March 13, 2026";

export default function TermsScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const theme = useThemeColors();
  const styles = useMemo(() => createStyles(theme), [theme]);
  const webTopInset = Platform.OS === "web" ? 67 : 0;

  return (
    <View style={[styles.container, { backgroundColor: theme.bg }]}>
      <View style={[styles.header, { paddingTop: (insets.top || webTopInset) + 8 }]}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn} accessibilityLabel="Go back" accessibilityRole="button">
          <ArrowLeft size={24} color={theme.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: theme.text }]}>Terms of Service</Text>
        <View style={{ width: 32 }} />
      </View>
      <ScrollView
        contentContainerStyle={[
          styles.scrollContent,
          { paddingBottom: Math.max(insets.bottom, Platform.OS === "web" ? 34 : 0) + 24 },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.version}>Version {TERMS_VERSION} — Effective {EFFECTIVE_DATE}</Text>

        <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.body}>
          By creating an account and using FoodVAR, you agree to these Terms of Service and our Privacy Policy. If you do not agree, please do not use the app.
        </Text>

        <Text style={styles.sectionTitle}>2. Service Description</Text>
        <Text style={styles.body}>
          FoodVAR provides personalized food health scores based on your health profile. You can scan barcodes, search for products, and receive dietary guidance. Scores are computed using a deterministic algorithm based on published nutritional data and your declared health profile.
        </Text>

        <Text style={styles.sectionTitle}>3. Medical Disclaimer</Text>
        <View style={styles.warningBox}>
          <Text style={styles.warningText}>
            FoodVAR is NOT a medical device and does NOT provide medical advice, diagnosis, or treatment. Health scores and dietary guidance are informational only and are based on general nutritional principles.
          </Text>
          <Text style={[styles.warningText, { marginTop: 8 }]}>
            Always consult a qualified healthcare professional before making dietary changes, especially if you have medical conditions, allergies, or take medications. Do not rely on FoodVAR scores to manage allergies or medical conditions.
          </Text>
        </View>

        <Text style={styles.sectionTitle}>4. AI-Generated Content Disclaimer</Text>
        <View style={styles.warningBox}>
          <Text style={styles.warningText}>
            Dietary advice in FoodVAR may be generated by artificial intelligence (Google Gemini). AI-generated content:{"\n"}
            {"\n"}• May contain inaccuracies or outdated information
            {"\n"}• Should not be treated as professional dietary or medical advice
            {"\n"}• Uses phrases like "may," "can," or "based on your profile" — not definitive claims
            {"\n"}• Cannot verify allergen safety of any product
            {"\n"}{"\n"}When AI is unavailable, the app falls back to deterministic scoring without AI-generated explanations.
          </Text>
        </View>

        <Text style={styles.sectionTitle}>5. Allergen Safety Warning</Text>
        <View style={styles.warningBox}>
          <Text style={styles.warningText}>
            FoodVAR flags potential allergens based on product data in our database. This data may be incomplete, outdated, or inaccurate. A score of 0 indicates a declared allergen match, but the absence of an allergen flag does NOT guarantee a product is safe. Always check product labels directly and consult your allergist.
          </Text>
        </View>

        <Text style={styles.sectionTitle}>6. User-Contributed Products</Text>
        <Text style={styles.body}>
          Users may contribute product information to the database. User-contributed products undergo a moderation review before being publicly visible. FoodVAR does not guarantee the accuracy of user-contributed data.
        </Text>

        <Text style={styles.sectionTitle}>7. Account & Data</Text>
        <Text style={styles.body}>
          You are responsible for maintaining the security of your account credentials. You may export your data or delete your account at any time through the Profile settings. Account deletion is irreversible and removes all associated data.
        </Text>

        <Text style={styles.sectionTitle}>8. Acceptable Use</Text>
        <Text style={styles.body}>
          You agree not to:{"\n"}
          {"\n"}• Submit false or misleading product information
          {"\n"}• Attempt to manipulate or abuse the scoring system
          {"\n"}• Use the app to provide medical advice to others
          {"\n"}• Reverse-engineer or misuse the AI advice system
        </Text>

        <Text style={styles.sectionTitle}>9. Limitation of Liability</Text>
        <Text style={styles.body}>
          FoodVAR is provided "as is" without warranties of any kind. We are not liable for any health outcomes, allergic reactions, or medical complications arising from the use of this app. Your use of FoodVAR is at your own risk.
        </Text>

        <Text style={styles.sectionTitle}>10. Changes to Terms</Text>
        <Text style={styles.body}>
          We may update these Terms from time to time. Material changes will be communicated through the app. Continued use after changes constitutes acceptance.
        </Text>
      </ScrollView>
    </View>
  );
}

const createStyles = (theme: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  header: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  backBtn: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: theme.text,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  version: {
    fontSize: 12,
    color: theme.placeholder,
    fontWeight: "500" as const,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: theme.text,
    marginTop: 20,
    marginBottom: 8,
  },
  body: {
    fontSize: 14,
    color: theme.muted,
    lineHeight: 22,
  },
  warningBox: {
    backgroundColor: "#FFF8E1",
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 3,
    borderLeftColor: "#FFA726",
  },
  warningText: {
    fontSize: 13,
    color: "#5D4037",
    lineHeight: 20,
  },
});
