// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/ActionMinimal.tsx": () => import("../components/mockups/home-redesign/ActionMinimal.tsx"),
  "./components/mockups/home-redesign/EditorialWellness.tsx": () => import("../components/mockups/home-redesign/EditorialWellness.tsx"),
  "./components/mockups/home-redesign/HealthDashboard.tsx": () => import("../components/mockups/home-redesign/HealthDashboard.tsx")
};
