// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bento-redesign/BentoHistory.tsx": () => import("../components/mockups/bento-redesign/BentoHistory.tsx"),
  "./components/mockups/bento-redesign/BentoHome.tsx": () => import("../components/mockups/bento-redesign/BentoHome.tsx"),
  "./components/mockups/bento-redesign/BentoProfile.tsx": () => import("../components/mockups/bento-redesign/BentoProfile.tsx"),
  "./components/mockups/bento-redesign/BentoResult.tsx": () => import("../components/mockups/bento-redesign/BentoResult.tsx"),
  "./components/mockups/bento-redesign/BentoScan.tsx": () => import("../components/mockups/bento-redesign/BentoScan.tsx"),
  "./components/mockups/bento-redesign-dark/BentoHistoryDark.tsx": () => import("../components/mockups/bento-redesign-dark/BentoHistoryDark.tsx"),
  "./components/mockups/bento-redesign-dark/BentoHomeDark.tsx": () => import("../components/mockups/bento-redesign-dark/BentoHomeDark.tsx"),
  "./components/mockups/bento-redesign-dark/BentoProfileDark.tsx": () => import("../components/mockups/bento-redesign-dark/BentoProfileDark.tsx"),
  "./components/mockups/bento-redesign-dark/BentoResultDark.tsx": () => import("../components/mockups/bento-redesign-dark/BentoResultDark.tsx"),
  "./components/mockups/bento-redesign-dark/BentoScanDark.tsx": () => import("../components/mockups/bento-redesign-dark/BentoScanDark.tsx"),
  "./components/mockups/home-redesign/ActionMinimal.tsx": () => import("../components/mockups/home-redesign/ActionMinimal.tsx"),
  "./components/mockups/home-redesign/EditorialWellness.tsx": () => import("../components/mockups/home-redesign/EditorialWellness.tsx"),
  "./components/mockups/home-redesign/HealthDashboard.tsx": () => import("../components/mockups/home-redesign/HealthDashboard.tsx"),
  "./components/mockups/home-refined/PremiumConsistency.tsx": () => import("../components/mockups/home-refined/PremiumConsistency.tsx"),
  "./components/mockups/home-refined/TighterPolish.tsx": () => import("../components/mockups/home-refined/TighterPolish.tsx"),
  "./components/mockups/profile-redesign/CardGrid.tsx": () => import("../components/mockups/profile-redesign/CardGrid.tsx"),
  "./components/mockups/profile-redesign/IdentityFirst.tsx": () => import("../components/mockups/profile-redesign/IdentityFirst.tsx"),
  "./components/mockups/profile-redesign/StatsForward.tsx": () => import("../components/mockups/profile-redesign/StatsForward.tsx"),
  "./components/mockups/home-refined-v2/DetailRefinement.tsx": () => import("../components/mockups/home-refined-v2/DetailRefinement.tsx"),
  "./components/mockups/home-refined-v2/FinalPolish.tsx": () => import("../components/mockups/home-refined-v2/FinalPolish.tsx"),
  "./components/mockups/tab-bar/FloatingGlass.tsx": () => import("../components/mockups/tab-bar/FloatingGlass.tsx"),
  "./components/mockups/tab-bar/MinimalEdge.tsx": () => import("../components/mockups/tab-bar/MinimalEdge.tsx"),
  "./components/mockups/tab-bar/NotchedDock.tsx": () => import("../components/mockups/tab-bar/NotchedDock.tsx")
};
