import { db } from "../server/db";
import { products } from "../shared/schema";
import { eq } from "drizzle-orm";

const SEED_PRODUCTS = [
  {
    barcode: "0049000006346",
    name: "Coca-Cola Classic",
    brand: "Coca-Cola",
    category: "Beverages",
    servingSize: "355ml (12 fl oz)",
    calories: 140,
    protein: 0,
    carbohydrates: 39,
    sugar: 39,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 45,
    declaredAllergens: [],
    ingredients: "Carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine",
  },
  {
    barcode: "0078000113464",
    name: "Cheerios Original",
    brand: "General Mills",
    category: "Cereals",
    servingSize: "28g (1 cup)",
    calories: 100,
    protein: 3,
    carbohydrates: 20,
    sugar: 1,
    fat: 2,
    saturatedFat: 0.5,
    fiber: 3,
    sodium: 140,
    declaredAllergens: ["wheat"],
    ingredients: "Whole grain oats, modified corn starch, sugar, salt, tripotassium phosphate, vitamin E",
  },
  {
    barcode: "0030000063170",
    name: "Quaker Oats Old Fashioned",
    brand: "Quaker",
    category: "Cereals",
    servingSize: "40g (0.5 cup dry)",
    calories: 150,
    protein: 5,
    carbohydrates: 27,
    sugar: 1,
    fat: 3,
    saturatedFat: 0.5,
    fiber: 4,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "100% whole grain rolled oats",
  },
  {
    barcode: "0011110038364",
    name: "Whole Milk",
    brand: "Kroger",
    category: "Dairy",
    servingSize: "240ml (1 cup)",
    calories: 150,
    protein: 8,
    carbohydrates: 12,
    sugar: 12,
    fat: 8,
    saturatedFat: 5,
    fiber: 0,
    sodium: 105,
    declaredAllergens: ["lactose"],
    ingredients: "Milk, vitamin D3",
  },
  {
    barcode: "0021130126026",
    name: "Baby Spinach",
    brand: "Organic Girl",
    category: "Vegetables",
    servingSize: "85g (3 oz)",
    calories: 20,
    protein: 2,
    carbohydrates: 3,
    sugar: 0,
    fat: 0,
    saturatedFat: 0,
    fiber: 2,
    sodium: 65,
    declaredAllergens: [],
    ingredients: "Organic baby spinach",
  },
  {
    barcode: "0038000138416",
    name: "Pringles Original",
    brand: "Pringles",
    category: "Snacks",
    servingSize: "28g (about 16 crisps)",
    calories: 150,
    protein: 1,
    carbohydrates: 15,
    sugar: 0,
    fat: 9,
    saturatedFat: 2.5,
    fiber: 1,
    sodium: 150,
    declaredAllergens: ["wheat"],
    ingredients: "Dried potatoes, vegetable oil, degerminated yellow corn flour, cornstarch, wheat starch, maltodextrin, salt",
  },
  {
    barcode: "0044000032173",
    name: "Oreo Cookies",
    brand: "Nabisco",
    category: "Snacks",
    servingSize: "34g (3 cookies)",
    calories: 160,
    protein: 1,
    carbohydrates: 25,
    sugar: 14,
    fat: 7,
    saturatedFat: 2,
    fiber: 1,
    sodium: 135,
    declaredAllergens: ["wheat", "soy"],
    ingredients: "Sugar, unbleached enriched flour, palm and/or canola oil, cocoa, high fructose corn syrup, leavening, cornstarch, salt, soy lecithin, vanillin, chocolate",
  },
  {
    barcode: "0021000658831",
    name: "Kraft Singles American Cheese",
    brand: "Kraft",
    category: "Dairy",
    servingSize: "21g (1 slice)",
    calories: 60,
    protein: 4,
    carbohydrates: 2,
    sugar: 1,
    fat: 4.5,
    saturatedFat: 2.5,
    fiber: 0,
    sodium: 250,
    declaredAllergens: ["lactose"],
    ingredients: "Cheddar cheese, milk, whey, milkfat, milk protein concentrate, salt, calcium phosphate, sodium citrate, whey protein concentrate, sodium phosphate, sorbic acid, apocarotenal, annatto, enzymes, cheese culture, vitamin D3",
  },
  {
    barcode: "0012000001086",
    name: "Pepsi",
    brand: "PepsiCo",
    category: "Beverages",
    servingSize: "355ml (12 fl oz)",
    calories: 150,
    protein: 0,
    carbohydrates: 41,
    sugar: 41,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 30,
    declaredAllergens: [],
    ingredients: "Carbonated water, high fructose corn syrup, caramel color, sugar, phosphoric acid, caffeine, citric acid, natural flavor",
  },
  {
    barcode: "0028400047708",
    name: "Doritos Nacho Cheese",
    brand: "Frito-Lay",
    category: "Snacks",
    servingSize: "28g (about 12 chips)",
    calories: 140,
    protein: 2,
    carbohydrates: 18,
    sugar: 1,
    fat: 8,
    saturatedFat: 1,
    fiber: 1,
    sodium: 210,
    declaredAllergens: ["lactose"],
    ingredients: "Corn, vegetable oil, maltodextrin, salt, cheddar cheese, whey, monosodium glutamate, buttermilk, romano cheese, whey protein concentrate, onion powder, corn flour, natural and artificial flavors, dextrose, tomato powder, spices, artificial color, lactic acid, citric acid, sugar, garlic powder, skim milk, red and green bell pepper powder, disodium inosinate, disodium guanylate",
  },
  {
    barcode: "0041570054215",
    name: "Nature Valley Granola Bars Oats 'n Honey",
    brand: "Nature Valley",
    category: "Snacks",
    servingSize: "42g (2 bars)",
    calories: 190,
    protein: 4,
    carbohydrates: 29,
    sugar: 12,
    fat: 6,
    saturatedFat: 0.5,
    fiber: 2,
    sodium: 180,
    declaredAllergens: ["wheat", "soy"],
    ingredients: "Whole grain oats, sugar, canola oil, yellow corn flour, honey, soy flour, brown sugar syrup, salt, soy lecithin, baking soda, natural flavor",
  },
  {
    barcode: "0036800440043",
    name: "Great Value Peanut Butter Creamy",
    brand: "Great Value",
    category: "Spreads",
    servingSize: "32g (2 tbsp)",
    calories: 190,
    protein: 7,
    carbohydrates: 7,
    sugar: 3,
    fat: 16,
    saturatedFat: 3,
    fiber: 2,
    sodium: 140,
    declaredAllergens: ["peanuts"],
    ingredients: "Roasted peanuts, sugar, contains 2% or less of molasses, fully hydrogenated vegetable oils, salt",
  },
  {
    barcode: "0041196910100",
    name: "Barilla Spaghetti",
    brand: "Barilla",
    category: "Pasta",
    servingSize: "56g (2 oz dry)",
    calories: 200,
    protein: 7,
    carbohydrates: 42,
    sugar: 2,
    fat: 1,
    saturatedFat: 0,
    fiber: 2,
    sodium: 0,
    declaredAllergens: ["wheat", "gluten"],
    ingredients: "Semolina (wheat), durum wheat flour, niacin, iron, thiamine mononitrate, riboflavin, folic acid",
  },
  {
    barcode: "0051000012517",
    name: "Campbell's Tomato Soup",
    brand: "Campbell's",
    category: "Canned Goods",
    servingSize: "124g (0.5 cup condensed)",
    calories: 90,
    protein: 2,
    carbohydrates: 20,
    sugar: 12,
    fat: 0,
    saturatedFat: 0,
    fiber: 1,
    sodium: 480,
    declaredAllergens: ["wheat"],
    ingredients: "Tomato puree, high fructose corn syrup, wheat flour, water, salt, potassium chloride, citric acid, flavoring, ascorbic acid",
  },
  {
    barcode: "0074682100914",
    name: "La Croix Sparkling Water Lime",
    brand: "La Croix",
    category: "Beverages",
    servingSize: "355ml (12 fl oz)",
    calories: 0,
    protein: 0,
    carbohydrates: 0,
    sugar: 0,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "Carbonated water, natural flavor",
  },
  {
    barcode: "0030000311097",
    name: "Life Cereal Original",
    brand: "Quaker",
    category: "Cereals",
    servingSize: "32g (0.75 cup)",
    calories: 120,
    protein: 3,
    carbohydrates: 25,
    sugar: 6,
    fat: 1.5,
    saturatedFat: 0,
    fiber: 2,
    sodium: 150,
    declaredAllergens: ["wheat"],
    ingredients: "Whole grain oat flour, sugar, corn flour, whole wheat flour, rice flour, salt, disodium phosphate, reduced iron, niacinamide, BHT, zinc oxide, thiamine mononitrate, pyridoxine hydrochloride, riboflavin, folic acid",
  },
  {
    barcode: "0070470433103",
    name: "Dave's Killer Bread 21 Whole Grains",
    brand: "Dave's Killer Bread",
    category: "Bakery",
    servingSize: "45g (1 slice)",
    calories: 110,
    protein: 5,
    carbohydrates: 22,
    sugar: 5,
    fat: 1.5,
    saturatedFat: 0,
    fiber: 5,
    sodium: 170,
    declaredAllergens: ["wheat", "soy", "gluten"],
    ingredients: "Organic whole wheat flour, water, organic cane sugar, organic cracked whole wheat, wheat gluten, organic oat fiber, organic sunflower seeds, organic flax seeds, yeast, organic molasses, organic sesame seeds, sea salt, organic cultured wheat starch, organic vinegar",
  },
  {
    barcode: "0013562300013",
    name: "Chobani Greek Yogurt Plain Non-Fat",
    brand: "Chobani",
    category: "Dairy",
    servingSize: "150g (5.3 oz)",
    calories: 80,
    protein: 14,
    carbohydrates: 6,
    sugar: 4,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 55,
    declaredAllergens: ["lactose"],
    ingredients: "Nonfat milk, live and active cultures: S. Thermophilus, L. Bulgaricus, L. Acidophilus, Bifidus, L. Casei",
  },
  {
    barcode: "0079893103167",
    name: "KIND Bar Dark Chocolate Nuts & Sea Salt",
    brand: "KIND",
    category: "Snacks",
    servingSize: "40g (1 bar)",
    calories: 180,
    protein: 6,
    carbohydrates: 16,
    sugar: 5,
    fat: 13,
    saturatedFat: 3.5,
    fiber: 7,
    sodium: 125,
    declaredAllergens: ["nuts", "soy"],
    ingredients: "Almonds, chicory root fiber, dark chocolate, honey, palm kernel oil, sugar, soy lecithin, sea salt, vanilla extract",
  },
  {
    barcode: "0041303000472",
    name: "Progresso Traditional Chicken Noodle Soup",
    brand: "Progresso",
    category: "Canned Goods",
    servingSize: "252g (1 cup)",
    calories: 100,
    protein: 7,
    carbohydrates: 12,
    sugar: 1,
    fat: 2.5,
    saturatedFat: 0.5,
    fiber: 1,
    sodium: 690,
    declaredAllergens: ["wheat", "eggs", "soy"],
    ingredients: "Chicken broth, enriched egg noodles, chicken meat, carrots, celery, modified corn starch, chicken fat, salt, monosodium glutamate, soy protein isolate, garlic powder, onion powder, spice, beta carotene for color",
  },
  {
    barcode: "0016000275645",
    name: "Annie's Organic Mac & Cheese",
    brand: "Annie's",
    category: "Pasta",
    servingSize: "70g (about 1 cup dry)",
    calories: 270,
    protein: 10,
    carbohydrates: 47,
    sugar: 5,
    fat: 4.5,
    saturatedFat: 2,
    fiber: 2,
    sodium: 550,
    declaredAllergens: ["wheat", "lactose", "gluten"],
    ingredients: "Organic pasta (organic wheat flour), organic cheddar cheese, whey, salt, sodium phosphate, annatto extract, turmeric, paprika",
  },
  {
    barcode: "0041390000102",
    name: "Bumble Bee Chunk Light Tuna in Water",
    brand: "Bumble Bee",
    category: "Canned Goods",
    servingSize: "56g (2 oz drained)",
    calories: 50,
    protein: 13,
    carbohydrates: 0,
    sugar: 0,
    fat: 0.5,
    saturatedFat: 0,
    fiber: 0,
    sodium: 180,
    declaredAllergens: ["fish"],
    ingredients: "Light tuna, water, vegetable broth, salt",
  },
  {
    barcode: "0072036700049",
    name: "Nature's Own 100% Whole Wheat Bread",
    brand: "Nature's Own",
    category: "Bakery",
    servingSize: "26g (1 slice)",
    calories: 60,
    protein: 4,
    carbohydrates: 12,
    sugar: 2,
    fat: 1,
    saturatedFat: 0,
    fiber: 2,
    sodium: 115,
    declaredAllergens: ["wheat", "soy", "gluten"],
    ingredients: "100% whole wheat flour, water, sugar, yeast, wheat gluten, soybean oil, salt, dough conditioners, calcium sulfate, monoglycerides, ethoxylated mono- and diglycerides, calcium propionate",
  },
  {
    barcode: "0024000163763",
    name: "Del Monte Diced Tomatoes",
    brand: "Del Monte",
    category: "Canned Goods",
    servingSize: "126g (0.5 cup)",
    calories: 25,
    protein: 1,
    carbohydrates: 6,
    sugar: 3,
    fat: 0,
    saturatedFat: 0,
    fiber: 1,
    sodium: 290,
    declaredAllergens: [],
    ingredients: "Tomatoes, tomato juice, citric acid, calcium chloride",
  },
  {
    barcode: "0048001211568",
    name: "Folgers Classic Roast Coffee",
    brand: "Folgers",
    category: "Beverages",
    servingSize: "2g (1 tbsp ground)",
    calories: 0,
    protein: 0,
    carbohydrates: 0,
    sugar: 0,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "100% pure coffee",
  },
  {
    barcode: "0070662006009",
    name: "Smucker's Strawberry Preserves",
    brand: "Smucker's",
    category: "Spreads",
    servingSize: "20g (1 tbsp)",
    calories: 50,
    protein: 0,
    carbohydrates: 13,
    sugar: 12,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "Strawberries, high fructose corn syrup, corn syrup, sugar, fruit pectin, citric acid",
  },
  {
    barcode: "0041268187805",
    name: "365 Organic Extra Virgin Olive Oil",
    brand: "365 Whole Foods",
    category: "Oils & Condiments",
    servingSize: "15ml (1 tbsp)",
    calories: 120,
    protein: 0,
    carbohydrates: 0,
    sugar: 0,
    fat: 14,
    saturatedFat: 2,
    fiber: 0,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "Organic extra virgin olive oil",
  },
  {
    barcode: "0038259113219",
    name: "Simple Truth Organic Baby Carrots",
    brand: "Simple Truth",
    category: "Vegetables",
    servingSize: "85g (about 8 carrots)",
    calories: 35,
    protein: 1,
    carbohydrates: 8,
    sugar: 5,
    fat: 0,
    saturatedFat: 0,
    fiber: 2,
    sodium: 80,
    declaredAllergens: [],
    ingredients: "Organic baby-cut carrots",
  },
  {
    barcode: "0041318420128",
    name: "Bush's Best Kidney Beans",
    brand: "Bush's",
    category: "Canned Goods",
    servingSize: "130g (0.5 cup)",
    calories: 110,
    protein: 7,
    carbohydrates: 19,
    sugar: 1,
    fat: 0,
    saturatedFat: 0,
    fiber: 6,
    sodium: 260,
    declaredAllergens: [],
    ingredients: "Prepared dark red kidney beans, water, sugar, salt, calcium chloride, calcium disodium EDTA",
  },
  {
    barcode: "0011110851383",
    name: "Kroger Large White Eggs",
    brand: "Kroger",
    category: "Dairy",
    servingSize: "50g (1 egg)",
    calories: 70,
    protein: 6,
    carbohydrates: 0,
    sugar: 0,
    fat: 5,
    saturatedFat: 1.5,
    fiber: 0,
    sodium: 70,
    declaredAllergens: ["eggs"],
    ingredients: "Eggs",
  },
  {
    barcode: "0016000457782",
    name: "Yoplait Original Strawberry Yogurt",
    brand: "Yoplait",
    category: "Dairy",
    servingSize: "170g (6 oz)",
    calories: 150,
    protein: 6,
    carbohydrates: 26,
    sugar: 22,
    fat: 2,
    saturatedFat: 1,
    fiber: 0,
    sodium: 80,
    declaredAllergens: ["lactose"],
    ingredients: "Cultured pasteurized grade A low fat milk, sugar, strawberries, modified corn starch, kosher gelatin, citric acid, tricalcium phosphate, natural flavor, pectin, colored with carmine, vitamin A acetate, vitamin D3",
  },
  {
    barcode: "0086600700045",
    name: "Justin's Classic Almond Butter",
    brand: "Justin's",
    category: "Spreads",
    servingSize: "32g (2 tbsp)",
    calories: 190,
    protein: 7,
    carbohydrates: 6,
    sugar: 2,
    fat: 16,
    saturatedFat: 2,
    fiber: 3,
    sodium: 0,
    declaredAllergens: ["nuts"],
    ingredients: "Dry roasted almonds, palm oil",
  },
  {
    barcode: "0737628064502",
    name: "Bob's Red Mill Gluten Free Oats",
    brand: "Bob's Red Mill",
    category: "Cereals",
    servingSize: "40g (0.5 cup)",
    calories: 150,
    protein: 5,
    carbohydrates: 27,
    sugar: 0,
    fat: 2.5,
    saturatedFat: 0.5,
    fiber: 4,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "Whole grain gluten free oats",
  },
  {
    barcode: "0075450140006",
    name: "Gardein Plant-Based Beefless Ground",
    brand: "Gardein",
    category: "Frozen",
    servingSize: "55g (about 1/3 cup)",
    calories: 90,
    protein: 14,
    carbohydrates: 6,
    sugar: 0,
    fat: 2.5,
    saturatedFat: 0,
    fiber: 3,
    sodium: 260,
    declaredAllergens: ["soy", "wheat"],
    ingredients: "Water, soy protein concentrate, expeller pressed canola oil, wheat gluten, soy protein isolate, modified vegetable gum, yeast extract, onion powder, beet powder, garlic powder, spices, sea salt, cane sugar, pea protein, natural flavor",
  },
  {
    barcode: "0011110700407",
    name: "Kroger Canned Green Beans",
    brand: "Kroger",
    category: "Canned Goods",
    servingSize: "121g (0.5 cup)",
    calories: 20,
    protein: 1,
    carbohydrates: 4,
    sugar: 1,
    fat: 0,
    saturatedFat: 0,
    fiber: 1,
    sodium: 380,
    declaredAllergens: [],
    ingredients: "Green beans, water, salt",
  },
  {
    barcode: "0011110000156",
    name: "Kroger Brown Rice Long Grain",
    brand: "Kroger",
    category: "Grains",
    servingSize: "45g (0.25 cup dry)",
    calories: 160,
    protein: 3,
    carbohydrates: 35,
    sugar: 0,
    fat: 1,
    saturatedFat: 0,
    fiber: 2,
    sodium: 0,
    declaredAllergens: [],
    ingredients: "Brown rice",
  },
  {
    barcode: "0022000017727",
    name: "M&M's Milk Chocolate",
    brand: "Mars",
    category: "Candy",
    servingSize: "42g (about 32 pieces)",
    calories: 200,
    protein: 2,
    carbohydrates: 30,
    sugar: 25,
    fat: 9,
    saturatedFat: 5,
    fiber: 1,
    sodium: 25,
    declaredAllergens: ["lactose", "soy"],
    ingredients: "Milk chocolate, sugar, cocoa butter, skim milk, chocolate, milkfat, lactose, peanuts, corn syrup, soy lecithin, dextrin, gum acacia, coloring, corn starch",
  },
  {
    barcode: "0011110857910",
    name: "Kroger Fat Free Skim Milk",
    brand: "Kroger",
    category: "Dairy",
    servingSize: "240ml (1 cup)",
    calories: 80,
    protein: 8,
    carbohydrates: 12,
    sugar: 12,
    fat: 0,
    saturatedFat: 0,
    fiber: 0,
    sodium: 130,
    declaredAllergens: ["lactose"],
    ingredients: "Fat free milk, vitamin A palmitate, vitamin D3",
  },
  {
    barcode: "0041196021578",
    name: "Barilla Penne Rigate",
    brand: "Barilla",
    category: "Pasta",
    servingSize: "56g (2 oz dry)",
    calories: 200,
    protein: 7,
    carbohydrates: 42,
    sugar: 2,
    fat: 1,
    saturatedFat: 0,
    fiber: 2,
    sodium: 0,
    declaredAllergens: ["wheat", "gluten"],
    ingredients: "Semolina (wheat), durum wheat flour, niacin, iron, thiamine mononitrate, riboflavin, folic acid",
  },
  {
    barcode: "0021908501314",
    name: "Silk Original Soy Milk",
    brand: "Silk",
    category: "Beverages",
    servingSize: "240ml (1 cup)",
    calories: 110,
    protein: 8,
    carbohydrates: 9,
    sugar: 6,
    fat: 4.5,
    saturatedFat: 0.5,
    fiber: 2,
    sodium: 75,
    declaredAllergens: ["soy"],
    ingredients: "Soymilk (filtered water, soybeans), cane sugar, sea salt, carrageenan, natural flavor, calcium carbonate, vitamin A palmitate, vitamin D2, riboflavin, vitamin B12",
  },
  {
    barcode: "0028400083102",
    name: "Lay's Classic Potato Chips",
    brand: "Lay's",
    category: "Snacks",
    servingSize: "28g (about 15 chips)",
    calories: 160,
    protein: 2,
    carbohydrates: 15,
    sugar: 0,
    fat: 10,
    saturatedFat: 1.5,
    fiber: 1,
    sodium: 170,
    declaredAllergens: [],
    ingredients: "Potatoes, vegetable oil (sunflower, corn, and/or canola oil), salt",
  },
  {
    barcode: "0018894115052",
    name: "RXBar Chocolate Sea Salt",
    brand: "RXBAR",
    category: "Snacks",
    servingSize: "52g (1 bar)",
    calories: 210,
    protein: 12,
    carbohydrates: 24,
    sugar: 13,
    fat: 9,
    saturatedFat: 2,
    fiber: 5,
    sodium: 260,
    declaredAllergens: ["eggs", "nuts"],
    ingredients: "Dates, egg whites, cashews, almonds, chocolate, cocoa, natural flavors, sea salt",
  },
  {
    barcode: "0041270040112",
    name: "Arnold Whole Wheat Bread",
    brand: "Arnold",
    category: "Bakery",
    servingSize: "38g (1 slice)",
    calories: 90,
    protein: 5,
    carbohydrates: 17,
    sugar: 3,
    fat: 1.5,
    saturatedFat: 0,
    fiber: 3,
    sodium: 130,
    declaredAllergens: ["wheat", "soy", "gluten"],
    ingredients: "Whole wheat flour, water, sugar, yeast, wheat gluten, soybean oil, salt, calcium sulfate, dough conditioners",
  },
  {
    barcode: "0044000031350",
    name: "Ritz Crackers Original",
    brand: "Nabisco",
    category: "Snacks",
    servingSize: "16g (5 crackers)",
    calories: 80,
    protein: 1,
    carbohydrates: 10,
    sugar: 2,
    fat: 4,
    saturatedFat: 1,
    fiber: 0,
    sodium: 105,
    declaredAllergens: ["wheat", "soy"],
    ingredients: "Unbleached enriched flour, soybean oil, sugar, salt, leavening, high fructose corn syrup, soy lecithin, malted barley flour, natural flavor",
  },
  {
    barcode: "0011213202587",
    name: "Lara Bar Peanut Butter Cookie",
    brand: "Larabar",
    category: "Snacks",
    servingSize: "48g (1 bar)",
    calories: 220,
    protein: 7,
    carbohydrates: 24,
    sugar: 17,
    fat: 12,
    saturatedFat: 2,
    fiber: 3,
    sodium: 85,
    declaredAllergens: ["peanuts"],
    ingredients: "Dates, peanuts, sea salt",
  },
  {
    barcode: "0029000076501",
    name: "Planters Dry Roasted Peanuts",
    brand: "Planters",
    category: "Snacks",
    servingSize: "28g (about 39 peanuts)",
    calories: 170,
    protein: 7,
    carbohydrates: 5,
    sugar: 2,
    fat: 14,
    saturatedFat: 2,
    fiber: 2,
    sodium: 160,
    declaredAllergens: ["peanuts"],
    ingredients: "Peanuts, sea salt, gelatin, maltodextrin, torula yeast, corn syrup solids, paprika, spices, onion and garlic powder, natural flavor",
  },
  {
    barcode: "0041498153014",
    name: "StarKist Chunk Light Tuna in Water Pouch",
    brand: "StarKist",
    category: "Canned Goods",
    servingSize: "56g (2 oz drained)",
    calories: 50,
    protein: 12,
    carbohydrates: 0,
    sugar: 0,
    fat: 0.5,
    saturatedFat: 0,
    fiber: 0,
    sodium: 140,
    declaredAllergens: ["fish"],
    ingredients: "Light tuna (skipjack), water, vegetable broth, salt",
  },
  {
    barcode: "0064420000506",
    name: "Clif Bar Chocolate Chip",
    brand: "Clif Bar",
    category: "Snacks",
    servingSize: "68g (1 bar)",
    calories: 250,
    protein: 10,
    carbohydrates: 44,
    sugar: 21,
    fat: 5,
    saturatedFat: 1.5,
    fiber: 4,
    sodium: 160,
    declaredAllergens: ["wheat", "soy", "lactose"],
    ingredients: "Organic brown rice syrup, organic rolled oats, soy protein isolate, organic cane syrup, organic oat fiber, rice flour, organic soy flour, organic date paste, cocoa, soy flour, barley malt extract, natural flavors, sea salt, soy lecithin",
  },
  {
    barcode: "0011110838094",
    name: "Kroger Frozen Broccoli Florets",
    brand: "Kroger",
    category: "Frozen",
    servingSize: "85g (about 4 florets)",
    calories: 25,
    protein: 2,
    carbohydrates: 4,
    sugar: 1,
    fat: 0,
    saturatedFat: 0,
    fiber: 2,
    sodium: 20,
    declaredAllergens: [],
    ingredients: "Broccoli",
  },
  {
    barcode: "0014500021908",
    name: "Skippy Creamy Peanut Butter",
    brand: "Skippy",
    category: "Spreads",
    servingSize: "33g (2 tbsp)",
    calories: 190,
    protein: 7,
    carbohydrates: 6,
    sugar: 3,
    fat: 16,
    saturatedFat: 3.5,
    fiber: 2,
    sodium: 150,
    declaredAllergens: ["peanuts"],
    ingredients: "Roasted peanuts, sugar, hydrogenated vegetable oil, salt",
  },
];

async function seed() {
  console.log(`Seeding ${SEED_PRODUCTS.length} products...`);
  let inserted = 0;
  let skipped = 0;

  for (const product of SEED_PRODUCTS) {
    const existing = await db
      .select({ id: products.id })
      .from(products)
      .where(eq(products.barcode, product.barcode))
      .limit(1);

    if (existing.length > 0) {
      skipped++;
      continue;
    }

    await db.insert(products).values({
      ...product,
      allergens: product.declaredAllergens,
      inferredAllergens: [],
      source: "seed",
      moderationStatus: "approved",
      verifiedAt: new Date(),
    });
    inserted++;
  }

  console.log(`Done. Inserted: ${inserted}, Skipped (duplicate): ${skipped}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
